In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"/content/Epoch Hackathon - Dataset.csv")
print(df.head())
df.info

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  k_value  l_value  m_value  percentage_free_sulphur  \
0      9.4 

<bound method DataFrame.info of       fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067

In [ ]:
df_new = df.drop_duplicates(ignore_index = True)
print(df_new.head())
df_new.info()

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.66         0.00             1.8      0.075   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 13.0                  40.0   0.9978  3.51       0.56   

   alcohol  quality  k_value  l_value  m_value  percentage_free_sulphur  \
0      9.4 

In [ ]:
Columns = df_new.columns.values
features = np.delete(Columns,11)
print(features)
parameters = df_new[features].values
print(parameters)

data = {}
for i in range(len(features)):
   data[features[i]] = parameters[:,i]
print(data)      

['fixed acidity' 'volatile acidity' 'citric acid' 'residual sugar'
 'chlorides' 'free sulfur dioxide' 'total sulfur dioxide' 'density' 'pH'
 'sulphates' 'alcohol' 'k_value' 'l_value' 'm_value'
 'percentage_free_sulphur' 'n_value']
[[ 7.4         0.7         0.         ...  0.636      30.90909091
   0.608     ]
 [ 7.8         0.88        0.         ...  0.778      26.8
   0.829     ]
 [ 7.8         0.76        0.04       ...  0.742      36.
   0.744     ]
 ...
 [ 5.9         0.55        0.1        ...  0.822      13.07692308
   0.711     ]
 [ 5.9         0.645       0.12       ...  0.785      13.75
   0.6615    ]
 [ 6.          0.31        0.47       ...  0.727      23.33333333
   1.2075    ]]
{'fixed acidity': array([7.4, 7.8, 7.8, ..., 5.9, 5.9, 6. ]), 'volatile acidity': array([0.7  , 0.88 , 0.76 , ..., 0.55 , 0.645, 0.31 ]), 'citric acid': array([0.  , 0.  , 0.04, ..., 0.1 , 0.12, 0.47]), 'residual sugar': array([1.9, 2.6, 2.3, ..., 2.2, 2. , 3.6]), 'chlorides': array([0.076, 0.098,

In [ ]:
labels = df_new[['quality']].values
print(labels)

[[0]
 [0]
 [0]
 ...
 [1]
 [0]
 [1]]


In [ ]:
# feature scaling - minmax method
min_parameters = np.array([])
max_parameters = np.array([])
for i in range(len(parameters[0])):
  min_parameters = np.append(min_parameters,np.min(parameters[:,i]))
  max_parameters = np.append(max_parameters,np.max(parameters[:,i]))

for i in range(len(parameters[0])):
  for j in range(len(parameters[:,i])):
    parameters[j][i] =(parameters[j][i] - min_parameters[i])/(max_parameters[i] - min_parameters[i])
print(parameters)

modified_data = {}
for i in range(len(features)):
  modified_data[features[i]] =parameters[:,i]

print(modified_data)


[[0.24778761 0.39726027 0.         ... 0.11161116 0.04492395 0.05403271]
 [0.28318584 0.52054795 0.         ... 0.17551755 0.03533074 0.10389171]
 [0.28318584 0.43835616 0.04       ... 0.15931593 0.05680934 0.08471517]
 ...
 [0.11504425 0.29452055 0.1        ... 0.19531953 0.00329243 0.07727016]
 [0.11504425 0.35958904 0.12       ... 0.17866787 0.00486381 0.06610265]
 [0.12389381 0.13013699 0.47       ... 0.15256526 0.02723735 0.1892837 ]]
{'fixed acidity': array([0.24778761, 0.28318584, 0.28318584, ..., 0.11504425, 0.11504425,
       0.12389381]), 'volatile acidity': array([0.39726027, 0.52054795, 0.43835616, ..., 0.29452055, 0.35958904,
       0.13013699]), 'citric acid': array([0.  , 0.  , 0.04, ..., 0.1 , 0.12, 0.47]), 'residual sugar': array([0.06849315, 0.11643836, 0.09589041, ..., 0.0890411 , 0.07534247,
       0.18493151]), 'chlorides': array([0.10684474, 0.14357262, 0.13355593, ..., 0.08347245, 0.10517529,
       0.0918197 ]), 'free sulfur dioxide': array([0.14084507, 0.338028

In [ ]:
# finding mean for each parameter.
mean_parameters = np.array([])
for i in range(len(parameters[0])):
 mean_parameters = np.append(mean_parameters,np.sum(parameters[:,i])/len(parameters[:]))
print(mean_parameters)  

[0.32837133 0.28046408 0.2723326  0.11119175 0.12708451 0.20976484
 0.1442614  0.4874411  0.44865087 0.1968293  0.31266391 0.33319065
 0.33319065 0.161489   0.04854325 0.10988115]


In [ ]:
sum = 0
# Finding the variance of each parameter
var_parameters = np.array([])
for i in range(len(parameters[0])):
   for j in range(len(parameters[:,i])):
       sum +=(parameters[j][i] - mean_parameters[i])**2
   var = sum/len(parameters[:])
   var_parameters = np.append(var_parameters,var)
   sum = 0
print(var_parameters)       

[0.02361119 0.01570455 0.03820641 0.00857294 0.00679006 0.02163562
 0.01392621 0.01881509 0.01489154 0.01043628 0.0276924  0.0231538
 0.0231538  0.00773442 0.00260154 0.00875987]


In [ ]:
sum = 0
# Finding the mean of labels.
for i in range(len(labels)):
   sum += labels[i][0]
mean_labels =  sum/len(labels)

print(mean_labels)
sum = 0
# Finding the varaince of labels.
for i in range(len(labels)):
    sum +=(labels[i][0] - mean_labels)**2
var_labels = sum/len(labels) 
print(var_labels)   
             




0.52906548933039
0.2491551973299893


In [ ]:
sum = 0
# Finding the covariance between each feature and quality.
co_var_parameters = np.array([])
for i in range(len(parameters[0])):
  for j in range(len(parameters[:,i])):
    sum +=(parameters[j][i] - mean_parameters[i])*(labels[j][0] -mean_labels)
  co_var = sum/len(parameters[:])
  co_var_parameters = np.append(co_var_parameters,co_var)
  sum = 0

print(co_var_parameters)


[ 0.00703807 -0.02046698  0.0163818  -0.00010958 -0.00473303 -0.00508126
 -0.01384534 -0.01156825  0.00028589  0.01077807  0.0370614   0.00444678
  0.00444678  0.00682461 -0.00359352  0.00031108]


In [ ]:
# Finding the correlation coefficient between each feature and quality
cor_coeff = np.array([])
for i in range(len(co_var_parameters)):
  cor_coeff = np.append(cor_coeff,co_var_parameters[i]/np.sqrt(var_parameters[i]*var_labels))
print(cor_coeff)  

[ 0.09176125 -0.32719465  0.16790301 -0.00237107 -0.11507149 -0.06920726
 -0.23504561 -0.16895832  0.0046935   0.21136501  0.44617631  0.05854636
  0.05854636  0.15546382 -0.14114632  0.00665859]


In [ ]:
dic = {}
for i in range(len(features)):
  dic[features[i]] = cor_coeff[i]
print(dic)  

{'fixed acidity': 0.09176125222443739, 'volatile acidity': -0.3271946452992922, 'citric acid': 0.1679030081538982, 'residual sugar': -0.0023710675527623334, 'chlorides': -0.11507149155054827, 'free sulfur dioxide': -0.06920725669412935, 'total sulfur dioxide': -0.23504560789081744, 'density': -0.16895831529316957, 'pH': 0.004693498113769304, 'sulphates': 0.21136501238035643, 'alcohol': 0.4461763137878795, 'k_value': 0.058546357769982064, 'l_value': 0.058546357769982064, 'm_value': 0.15546382427539013, 'percentage_free_sulphur': -0.14114631652794463, 'n_value': 0.0066585857951475536}


In [ ]:
# correlation coeff. is the indicator of how strong the relationship between the two variables. Here we neglect the features whose abs corr.coef with the label(quality) close to zero.
# Here we will consider features whose abs corr.coef is greater than 0.1
new_dic={}
for i in features:
   if abs(dic[i]) - 0.1 > 1e-9:
     new_dic[i] = dic[i]
print(new_dic)     


{'volatile acidity': -0.3271946452992922, 'citric acid': 0.1679030081538982, 'chlorides': -0.11507149155054827, 'total sulfur dioxide': -0.23504560789081744, 'density': -0.16895831529316957, 'sulphates': 0.21136501238035643, 'alcohol': 0.4461763137878795, 'm_value': 0.15546382427539013, 'percentage_free_sulphur': -0.14114631652794463}


In [ ]:
# Final data.
index_features = []
for i in range(len(features)):
  if features[i] in new_dic.keys():
    index_features.append(i)
print(index_features)

final_parameters = parameters[:,index_features]
print(final_parameters)


[1, 2, 4, 6, 7, 9, 10, 13, 14]
[[0.39726027 0.         0.10684474 ... 0.15384615 0.11161116 0.04492395]
 [0.52054795 0.         0.14357262 ... 0.21538462 0.17551755 0.03533074]
 [0.43835616 0.04       0.13355593 ... 0.21538462 0.15931593 0.05680934]
 ...
 [0.29452055 0.1        0.08347245 ... 0.43076923 0.19531953 0.00329243]
 [0.35958904 0.12       0.10517529 ... 0.27692308 0.17866787 0.00486381]
 [0.13013699 0.47       0.0918197  ... 0.4        0.15256526 0.02723735]]


In [ ]:
# Training

# dividing the data into training and test data in 80-20 ratio.
train_data = final_parameters[:int(4*len(final_parameters)/5),:]
test_data = final_parameters[int(4*len(final_parameters)/5):len(final_parameters),:]
# labels
train_labels = labels[:int(4*len(labels)/5),:]
test_labels = labels[int(4*len(labels)/5):len(labels),:]

print(train_data)

[[0.39726027 0.         0.10684474 ... 0.15384615 0.11161116 0.04492395]
 [0.52054795 0.         0.14357262 ... 0.21538462 0.17551755 0.03533074]
 [0.43835616 0.04       0.13355593 ... 0.21538462 0.15931593 0.05680934]
 ...
 [0.23287671 0.         0.10851419 ... 0.43076923 0.09855986 0.01385214]
 [0.31506849 0.2        0.10183639 ... 0.13846154 0.05175518 0.00297551]
 [0.31506849 0.13       0.15025042 ... 0.43076923 0.10981098 0.02220188]]


In [ ]:
# generating weight vector and bias 
weights_vector = np.random.random((len(index_features),1))
bias = 0.02
print(weights_vector)


[[0.37817574]
 [0.16495572]
 [0.54838422]
 [0.19650229]
 [0.98543274]
 [0.05553732]
 [0.42056963]
 [0.36580043]
 [0.78036416]]


In [ ]:
# Learning rate
lr = 0.01

def sigmoid(z):
 return 1/(1+np.exp(-z))

 # Iteration
for i in range(100000): 
 z = np.dot(train_data,weights_vector) + bias
 prob = sigmoid(z)

# cost function
 J = (-1)*(np.dot(np.log(prob).T,train_labels) + np.dot(np.log(1-prob).T,1-train_labels))/len(train_data)

# modifying the weight vector.
 for i in range(len(weights_vector)): 
   weights_vector[i] =  weights_vector[i] -lr*(np.dot((prob-train_labels).T,train_data[:,i]))/len(train_data)

 # modifying the bias.
 bias = bias - (np.sum(prob - train_labels))/len(train_data)



# New Section

# New Section

In [ ]:
# Testing

test_z =  np.dot(test_data,weights_vector) + bias
pred_prob = sigmoid(test_z)
print(pred_prob) # Predicted probabilities of test data

pred_labels = np.array([])

for i in range(len(pred_prob)):
 if pred_prob[i] - 0.5 > 1e-9:
   pred_labels = np.append(pred_labels,1)
 else :
   pred_labels = np.append(pred_labels,0)  
print(pred_labels) # Predicted labels of test data


[[0.14023741]
 [0.9285396 ]
 [0.36091188]
 [0.91942145]
 [0.59793148]
 [0.59153091]
 [0.34532496]
 [0.75359343]
 [0.65956906]
 [0.96707714]
 [0.93286103]
 [0.46666768]
 [0.62229084]
 [0.60221776]
 [0.94983906]
 [0.2874186 ]
 [0.16247221]
 [0.89223283]
 [0.88927821]
 [0.06987586]
 [0.88808299]
 [0.60027733]
 [0.90262819]
 [0.82314795]
 [0.09075519]
 [0.21747646]
 [0.22780189]
 [0.62616578]
 [0.20205002]
 [0.94365236]
 [0.13081103]
 [0.51987001]
 [0.50303335]
 [0.20809001]
 [0.83733621]
 [0.88359711]
 [0.16433188]
 [0.25750242]
 [0.83733621]
 [0.89085589]
 [0.83349406]
 [0.68893027]
 [0.31190816]
 [0.21801253]
 [0.07054742]
 [0.49495728]
 [0.17786665]
 [0.26344389]
 [0.91153277]
 [0.39409259]
 [0.6112326 ]
 [0.55116772]
 [0.78003277]
 [0.61073289]
 [0.8014105 ]
 [0.28550253]
 [0.59632997]
 [0.31325637]
 [0.75545398]
 [0.33464797]
 [0.4450474 ]
 [0.61483314]
 [0.61292826]
 [0.70061147]
 [0.10876893]
 [0.57043632]
 [0.63329774]
 [0.20400364]
 [0.14650371]
 [0.78723069]
 [0.35865564]
 [0.22

In [ ]:
correct_pred = 0

for i in range(len(test_labels)):
  if int(pred_labels[i]) == test_labels[i][0]:
     correct_pred +=1
accuracy = correct_pred*100/len(test_labels) # Accuracy of the model  
print(accuracy)

72.79411764705883
